- name: setup Apache on hosts in the web servers
  become: true
  hosts: web
  tasks: 
    - name: Install the latest version of Apache web server # and prerequisite for Wordpress
      apt: name="{{ item }}" update_cache=yes state=latest
      with_items:
      - apache2
      # - mysql-server
      # - php-mysql
      # - php
      # - libapache2-mod-php
      

    - name: Start Apache service
      service: name=apache2 state=started
    
  #   - name: Install php extensions
  #     apt: name="{{ item }}" state=present
  #     become: true
  #     with_items:
  #     - php-gd
  #     - php-ssh2

  #   - name: Download WordPress
  #     get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no

  #   - name: Extract WordPress
  #     unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  #     become: true

  #   - name: Update default Apache site
  #     become: true
  #     lineinfile: dest=/etc/apache2/sites-enabled/000-default.conf regexp="(.)+DocumentRoot /var/www/html" line="DocumentRoot /var/www/wordpress"

  #   - name: Copy sample config file
  #     command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  #     become: true

  #   - name: Replace database name in wp-config.php file
  #     become: true
  #     replace:
  #       path: /var/www/wordpress/wp-config.php
  #       regexp: 'database_name_here'
  #       replace: '{{ DB_NAME }}'

  #   - name: Replace database username in wp-config.php file
  #     become: true
  #     replace:
  #       path: /var/www/wordpress/wp-config.php
  #       regexp: 'username_here'
  #       replace: '{{ DB_USER }}'

  #   - name: Replace database password in wp-config.php file
  #     become: true
  #     replace:
  #       path: /var/www/wordpress/wp-config.php
  #       regexp: 'password_here'
  #       replace: '{{ DB_PASSWORD }}'

  #   - name: Restart Apache service
  #     service:
  #       name: apache2
  #       state: restarted

  # vars:
  #     DB_NAME: my_db
  #     DB_USER: my_user
  #     DB_PASSWORD: my_password



